version: '3'

services:
  goapp: 
    build: .
    container_name: goapp
    volumes:
      - .:/app

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=orders
    volumes:
      - ./.docker/mysql:/var/lib/mysql